REDIS_CLI=../../deps/redis/src/redis-cli

echo "SET GRAPH"
$REDIS_CLI -x AI.SET GRAPH foo TF GPU < graph.pb

echo "SET TENSORS"
$REDIS_CLI AI.SET TENSOR a FLOAT 1 2 VALUES 2 3
$REDIS_CLI AI.SET TENSOR b FLOAT 1 2 VALUES 2 3

echo "GET TENSORS"
$REDIS_CLI AI.GET TENSOR a VALUES
$REDIS_CLI AI.GET TENSOR b VALUES

echo "RUN GRAPH"
$REDIS_CLI AI.RUN GRAPH foo
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a b NAMES a b OUTPUTS
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a b NAMES a b OUTPUTS
$REDIS_CLI AI.RUN GRAPH foo OUTPUTS 1 c NAMES mul
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a OUTPUTS 1 c NAMES mul
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a b NAMES a OUTPUTS 1 c NAMES mul
$REDIS_CLI AI.RUN GRAPH foo INPUTS 2 a b NAMES a b OUTPUTS 1 c NAMES mul

echo "GET TENSOR META"
$REDIS_CLI AI.GET TENSOR c META

echo "GET TENSOR VALUES"
$REDIS_CLI AI.GET TENSOR c VALUES

echo "GET TENSOR BLOB"
#$REDIS_CLI --raw AI.GET TENSOR c BLOB
$REDIS_CLI AI.GET TENSOR c BLOB

