REDIS_CLI=../../deps/redis/src/redis-cli

echo "SET SCRIPT"
$REDIS_CLI -x AI.SET SCRIPT foo CPU < script.txt

echo "SET TENSORS"
$REDIS_CLI AI.SET TENSOR a FLOAT 1 2 VALUES 2 3
$REDIS_CLI AI.SET TENSOR b FLOAT 1 2 VALUES 2 3

echo "GET TENSORS"
$REDIS_CLI AI.GET TENSOR a VALUES
$REDIS_CLI AI.GET TENSOR b VALUES

echo "RUN SCRIPT"
$REDIS_CLI AI.RUN SCRIPT foo bar 2 a a b b c c
# $REDIS_CLI AI.RUN SCRIPT foo bar 2 a b c

echo "GET TENSOR META"
$REDIS_CLI AI.GET TENSOR c META

echo "GET TENSOR VALUES"
$REDIS_CLI AI.GET TENSOR c VALUES

echo "GET TENSOR BLOB"
#$REDIS_CLI --raw AI.GET TENSOR c BLOB
$REDIS_CLI AI.GET TENSOR c BLOB

