# BUILD redisfab/redisai:${VERSION}-gpu-${ARCH}-${OSNICK}-test

ARG REDIS_VER=6.2.1

# OSNICK=bionic|centos7|centos6
ARG OSNICK=bionic

# ARCH=x64|arm64v8|arm32v7
ARG ARCH=x64

# OS=ubuntu18.04|ubuntu16.04|centos7
ARG OS=ubuntu18.04

ARG CUDA_VER=10.1-cudnn7

ARG PACK=1

#----------------------------------------------------------------------------------------------
FROM redisfab/redis:${REDIS_VER}-${ARCH}-${OSNICK} AS redis
FROM nvidia/cuda:${CUDA_VER}-devel-${OS} AS builder

SHELL ["/bin/bash", "-c"]

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

WORKDIR /build
COPY --from=redis /usr/local/ /usr/local/

COPY ./opt/ opt/
COPY ./tests/flow/test_requirements.txt tests/flow/

RUN VENV=venv FORCE=1 ./opt/readies/bin/getpy3

RUN set -e ;\
	. venv/bin/activate ;\
	./opt/system-setup.py

ARG DEPS_ARGS=""
COPY ./get_deps.sh .
RUN set -e ;\
	. venv/bin/activate ;\
	if [[ -z $DEPS_ARGS ]]; then \
		VERBOSE=1 ./get_deps.sh gpu ;\
	else \
		env $DEPS_ARGS ./get_deps.sh gpu ;\
	fi

ARG BUILD_ARGS=""
ADD ./ /build
RUN set -e ;\
	. venv/bin/activate ;\
	bash -l -c "make -C opt build GPU=1 $BUILD_ARGS SHOW=1"

ARG PACK

RUN set -e ;\
	if [[ $PACK == 1 ]]; then \
		. venv/bin/activate ;\
		bash -l -c "make -C opt pack GPU=1 VERBOSE=1" ;\
	fi

RUN git remote set-url origin https://github.com/RedisAI/RedisAI

CMD ["bash", "-c", ". ./venv/bin/activate; make -C opt test GPU=1 SHOW=1"]
