name: Deploy docs to website

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    paths:
      - 'mkdocs.yml'
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install Doxygen
      run: apt-get install -y doxygen
    - name: Install docs dependencies
      run: pip install -r docs/requirements.txt
    - name: Build C API reference
      run: cd docs && python3 generate_llapi_reference.py && cd ..
    - name: Build docs
      run: mkdocs build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.DOCS_AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET_ACCESS_KEY }}
        DEST_DIR: ${{ secrets.DOCS_AWS_S3_DIR }}
        SOURCE_DIR: 'site'
