REDIS_CLI=../deps/redis/src/redis-cli

echo "SET GRAPH"
$REDIS_CLI -x TF.GRAPH foo < graph.pb

echo "SET TENSORS"
$REDIS_CLI TF.TENSOR a FLOAT 1 2 VALUES 2 3
$REDIS_CLI TF.TENSOR b FLOAT 1 2 VALUES 2 3

echo "GET TENSORS"
$REDIS_CLI TF.VALUES a
$REDIS_CLI TF.VALUES b

echo "RUN GRAPH"
$REDIS_CLI TF.RUN foo 2 a a b b c mul

echo "GET TENSOR"
$REDIS_CLI TF.VALUES c

echo "GET TENSOR RAW"
$REDIS_CLI --raw TF.DATA c

echo "NDIMS" `$REDIS_CLI TF.NDIMS c`

echo "DIMS" `$REDIS_CLI TF.DIMS c`

echo "TYPE" `$REDIS_CLI TF.TYPE c`

echo "SIZE" `$REDIS_CLI TF.SIZE c`

