REDIS_CLI=../deps/redis/src/redis-cli

echo "SET GRAPH"
$REDIS_CLI -x TF.GRAPH foo < graph.pb

echo "SET TENSORS"
$REDIS_CLI TF.TENSOR a FLOAT 1 2 VALUES 2 3
$REDIS_CLI TF.TENSOR b FLOAT 1 2 VALUES 2 3

echo "GET TENSORS"
$REDIS_CLI TF.VALUES a
$REDIS_CLI TF.VALUES b

echo "RUN GRAPH"
$REDIS_CLI TF.RUN foo 2 a a b b c mul

echo "GET TENSOR"
$REDIS_CLI --raw TF.DATA c
$REDIS_CLI TF.VALUES c

